version: 0.0
os: linux
files:
  - source: /docs/build/html/
    destination: /tmp/code-deploy-bot_identifier
hooks:
  BeforeInstall:
    - location: scripts/01-create-folder.sh
    - location: scripts/02-clean-build.sh
  AfterInstall:
    - location: scripts/03-move-files.sh
    - location: scripts/04-set-permissions.sh