version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - apt-get install python3-pip -y
      - pip3 install sphinx sphinx_rtd_theme sphinx-sitemap
      # - pip3 install guzzle_sphinx_theme
  build:
    commands:
      - sed -i "s/BOT_IDENTIFIER/$BOT_IDENTIFIER/g" appspec.yml
      - sed -i "s/BOT_IDENTIFIER/$BOT_IDENTIFIER/g" $(find scripts/ -type f)
      - cd docs/
      - make clean html

artifacts:
  files:
    - docs/build/html/**/*
    - appspec.yml
    - scripts/01-create-folder.sh
    - scripts/02-clean-build.sh
    - scripts/03-move-files.sh
    - scripts/04-set-permissions.sh
  discard-paths: no